### PR TITLE
PW-7988: Upgrade to Checkout v70 

### PR DESCRIPTION
**Pull request by michaelpaul**
## Summary

This change adds support for [Checkout v70](https://docs.adyen.com/api-explorer/Checkout/70/overview). It also includes data type changes and new names for some endpoints.

### CODE REVIEW

**Review by wboereboom — COMMENTED** [review]
Lots of renames for payment methods. any way we can keep those te same to reduce breakage?

**Comment by michaelpaul** [comment]
> Lots of renames for payment methods. any way we can keep those te same to reduce breakage?

Sure, we can rename models or endpoints on a spec level, just file a separate ticket with the suggestions.

**Comment by wboereboom** [comment]
Eventually I would like to change them I think. it's this specific Lib that has different names from all the other ones :(

**Comment by michaelpaul** [comment]
> Eventually I would like to change them I think. it's this specific Lib that has different names from all the other ones :(

All the names came from the spec now. Other libraries will have the same name once they are implement/generate services from specs.

**Review by AlexandrosMor — APPROVED** [review]

**Review by wboereboom — APPROVED** [review]

**Pull request merged**
