### PR TITLE
Recurrent India

### PR DESCRIPTION
**Pull request by mderasse**
## Summary
Adding missing endpoint to allow implementation of the recurring in india
https://docs.adyen.com/payment-methods/cards/cards-recurring-india

## Tested scenarios
Recurring workflow

**Fixed issue**: N/A

### CODE REVIEW

**Review by acampos1916 — CHANGES_REQUESTED** [review]
Thanks for this contribution @mderasse! Really appreciate it. Could you add tests to the new functionality?

**Comment by mderasse** [comment]
It seems like lot of test are not going through ...
Could we prod that PR ? We also got the information that anyway in a near future a new sdk version will be created on your end (using more recent api version).

**Comment by acampos1916** [comment]
@mderasse indeed tests are not passing for contributors not in the Adyen organization because you don't have access to the secrets containing the API credentials, but these should be configurable and passing in your local environment.

**Comment by mderasse** [comment]
Done

**Review by acampos1916 — APPROVED** [review]

**Pull request merged**
